name: ci
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Backend modules 
        uses: cypress-io/github-action@v2
        with:
          install-command: npm run install:backend
          runTests: false
      - name: Install Frontend modules 
        uses: cypress-io/github-action@v2
        with:
          install-command: npm run install:frontend
          runTests: false
      - name: Static Analysis with ESLint
        with:
          command: npm run eslint:frontend, npm run eslint:backend
      - name: Cypress E2E tests 🧪
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:frontend, npm run start:backend
          command: npm run run:cypress:tests
