name: ci
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install frontend modules 
        uses: cypress-io/github-action@v5
        with:
          install-command: npm run install:frontend
          runTests: false
      - name: Cypress E2E tests 🧪
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:frontend, npm run start:backend
          command: npm run run-cypress-tests
