name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Dependencies 
        run: npm install
      - name: Install Cypress 
        run: npm install cypress --save-dev
      - name: Cypress.io
        uses: cypress-io/github-action@v5.1.0

