name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Dependencies 
        uses: npi ci
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with: 
          browser: chrome
          headless: true
          star: npm run dev
          wait-on: http://localhost:3000
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

